/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package transactionaccount;

import com.formdev.flatlaf.FlatDarculaLaf;
import com.formdev.flatlaf.FlatDarkLaf;
import javax.swing.SwingUtilities;
import transactionaccount.views.MainView;
import transactionaccount.views.TransactionView;

public class App {

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        FlatDarkLaf.setup();
        
        //FlatDarculaLaf.setup();
        //SwingUtilities.invokeLater(MainView::new);
        SwingUtilities.invokeLater(TransactionView::new);
    }
}
